package com.my13each.dooray.mcp.constants

object EnvVariableConst {

    val DOORAY_BASE_URL = "DOORAY_BASE_URL"
    val DOORAY_API_KEY = "DOORAY_API_KEY"
    val DOORAY_TEST_PROJECT_ID = "DOORAY_TEST_PROJECT_ID"
    val DOORAY_TEST_WIKI_ID = "DOORAY_TEST_WIKI_ID"
    val DOORAY_ENABLED_CATEGORIES = "DOORAY_ENABLED_CATEGORIES"
}
